# Generated by Django 3.2.8 on 2021-10-10 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(help_text='Jaki masz dzisiaj cel', max_length=100)),
                ('slug', models.SlugField(max_length=100, unique_for_date='created')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(help_text='Od kiedy zaczynasz ?')),
                ('end_date', models.DateTimeField(help_text='Do kiedy planujesz sończyć ?')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='Informacje na temat zadania', max_length=300)),
                ('status', models.CharField(choices=[('start', 'Start'), ('in_progress', 'In progress'), ('finished', 'Finished')], default='S', max_length=15)),
                ('difficulty_classification', models.CharField(choices=[('hard', 'Hard'), ('medium', 'Medium'), ('easy', 'Easy')], help_text='Jak trudne może być to zadanie ? ', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-end_date',),
            },
        ),
    ]
